security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        doctrine:
            entity:
                class: App\Entity\User\User
                property: username

    encoders:
        App\Entity\User\AbstractUser:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: doctrine

            guard:
                authenticators:
                    - App\Security\Authenticator\FormAuthenticator

            logout:
                path: app_security_logout
                target: app_security_login

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }
